### ISSUE TITLE
 actionAdmin() in controller throws an php error after generating it with gii mongocrud

### ISSUE THREAD

**Issue by mariuskubilius** [canni/YiiMongoDbSuite#20]
Have problem when trying to access admin action it throws php error: full error output is below:
PHP Error
Description

Undefined index: Country
Source File

C:\web\ski\protected\extensions\YiiMongoDbSuite\EMongoDocument.php(331)

00319:      \* Get value of use cursor flag
00320:      *
00321:      \* It will return the nearest not null value in order:
00322:      \* - Object level
00323:      \* - Model level
00324:      \* - Glopal level (always set)
00325:      \* @return boolean
00326:      _/
00327:     public function getUseCursor()
00328:     {
00329:         if($this->useCursor !== null)
00330:             return $this->useCursor; // We have flag set, return it
00331: if(self::$_models[get_class($this)]->useCursor !== null)
00332:             return self::$_models[get_class($this)]->useCursor; // Model have flag set, return it
00333:         return $this->getMongoDBComponent()->useCursor;
00334:     }
00335: 
00336:     /_*
00337:      \* Set object level value of use cursor flag
00338:      \* @param boolean $useCursor true|false value for use cursor flag
00339:      */
00340:     public function setUseCursor($useCursor)
00341:     {
00342:         $this->useCursor = ($useCursor == true);
00343:     }

Stack Trace
#0 C:\web\ski\protected\extensions\YiiMongoDbSuite\EMongoDocument.php(826): Country->getUseCursor()
#1 C:\web\ski\protected\extensions\YiiMongoDbSuite\EMongoDocumentDataProvider.php(141): Country->findAll()
#2 C:\yii\framework\web\CDataProvider.php(128): EMongoDocumentDataProvider->fetchData()
#3 C:\yii\framework\zii\widgets\CBaseListView.php(105): EMongoDocumentDataProvider->getData()
#4 C:\yii\framework\zii\widgets\grid\CGridView.php(220): CGridView->init()
#5 C:\yii\framework\web\CBaseController.php(140): CGridView->init()
#6 C:\yii\framework\web\CBaseController.php(165): CountryController->createWidget()
#7 C:\web\ski\protected\views\country\admin.php(61): CountryController->widget()
#8 C:\yii\framework\web\CBaseController.php(119): require()
#9 C:\yii\framework\web\CBaseController.php(88): CountryController->renderInternal()
#10 C:\yii\framework\web\CController.php(833): CountryController->renderFile()
#11 C:\yii\framework\web\CController.php(746): CountryController->renderPartial()
#12 C:\web\ski\protected\controllers\CountryController.php(149): CountryController->render()
#13 C:\yii\framework\web\actions\CInlineAction.php(57): CountryController->actionAdmin()
#14 C:\yii\framework\web\CController.php(300): CInlineAction->run()
#15 C:\yii\framework\web\filters\CFilterChain.php(133): CountryController->runAction()
#16 C:\yii\framework\web\filters\CFilter.php(41): CFilterChain->run()
#17 C:\yii\framework\web\CController.php(1084): CAccessControlFilter->filter()
#18 C:\yii\framework\web\filters\CInlineFilter.php(59): CountryController->filterAccessControl()
#19 C:\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#20 C:\yii\framework\web\CController.php(283): CFilterChain->run()
#21 C:\yii\framework\web\CController.php(257): CountryController->runActionWithFilters()
#22 C:\yii\framework\web\CWebApplication.php(324): CountryController->run()
#23 C:\yii\framework\web\CWebApplication.php(121): CWebApplication->runController()
#24 C:\yii\framework\base\CApplication.php(135): CWebApplication->processRequest()
#25 C:\web\ski\index.php(13): CWebApplication->run()

**Comment by canni** [comment]
This problem is fixed in developement branch, It will be included in next release.

For now, checkout those line in devel branch source, or switch Yours repo copy to devel branch,

cheers
