### ISSUE TITLE
Strange error

### ISSUE THREAD

**Issue by bitshine** [canni/YiiMongoDbSuite#25]
I use Gii MongoCURD to gen codes

when access admin page get below error:

PHP Error
Description
Undefined index: Feed
Source File
D:\www\feed\feed.cdeledu.com\protected\extensions\YiiMongoDbSuite\EMongoDocument.php(331)
00319:      \* Get value of use cursor flag
00320:      *
00321:      \* It will return the nearest not null value in order:
00322:      \* - Object level
00323:      \* - Model level
00324:      \* - Glopal level (always set)
00325:      \* @return boolean
00326:      */
00327:     public function getUseCursor()
00328:     {
00329:         if($this->useCursor !== null)
00330:             return $this->useCursor; // We have flag set, return it

00320:      *
00321:      \* It will return the nearest not null value in order:
00322:      \* - Object level
00323:      \* - Model level
00324:      \* - Glopal level (always set)
00325:      \* @return boolean
00326:      */
00327:     public function getUseCursor()
00328:     {
00329:         if($this->useCursor !== null)
00330:             return $this->useCursor; // We have flag set, return it

00320:      *
ot null value in order:
00322:      \* - Object level
00323:      \* - Model level
00324:      \* - Glopal level (always set)
00325:      *

why $_models is empty?

**Comment by canni** [comment]
It is known bug, and it's fixed in current development branch, this fix will be in upcoming release 1.3.6

Checkout how that line looks in devel branch or wait till 1.3.6 is released :)

cheers
