### ISSUE TITLE
EMongoDocument::init Indexed Key Unique Bug

### ISSUE THREAD

**Issue by alzerid** [canni/YiiMongoDbSuite#26]
Int EMongoDocument::init, the logic grabs all the indices for that mongo collection.  The code also assumes that all indices are unique.  The code:
        $indexes[$index['name']] = array(
          'key'=>$index['key'],
          'unique'=>$index['unique'],
        );  

Breaks if the index is NOT unique.  Need to add logic there to check if the key is unique or not before indexing 'unique'.

**Comment by canni** [comment]
thanks for pointing it out, fixed
