### ISSUE TITLE
Undefined index on EMongoModifier

### ISSUE THREAD

**Issue by josemartinez** [canni/YiiMongoDbSuite#27]
Hi canni, 

I found a bug on EMongoModifier.php file in line 98

we can get an Exception "Undefined index" on the following line

is_array($modifier[$operator])

Of course, you will only get this error if your server is configured to report notices. 

You can fix it changing the line by the following: 

if(isset($modifier[$operator]) && is_array($modifier[$operator]))  // we check before if index is set

Best regards

**Comment by canni** [comment]
Fixed, Thanks :)
