### ISSUE TITLE
broken yiii shell

### ISSUE THREAD

**Issue by lpanebr** [canni/YiiMongoDbSuite#28]
Hello,

When I try the yiic shell on a normal project (mysql) it works. But on a projecy using YiiMongoDbSuite it outputs the html generated for an error page as follows:

<pre>
<div class="container">
    <h1>PHP Error</h1>

    <p class="message">
        include(Mongo.php): failed to open stream: No such file or directory    </p>

    <div class="source">
        <p class="file">/home/lpanebr/Libraries/webdev/yii-1.1.6.r2877/framework/YiiBase.php(395)</p>
        <div class="code"><pre><span class="ln">383</span>      * @return boolean whether the class has been loaded successfully
<span class="ln">384</span>      */
<span class="ln">385</span>     public static function autoload($className)
<span class="ln">386</span>     {
<span class="ln">387</span>         // use include so that the error PHP file may appear
<span class="ln">388</span>         if(isset(self::$_coreClasses[$className]))
<span class="ln">389</span>             include(YII_PATH.self::$_coreClasses[$className]);
<span class="ln">390</span>         else if(isset(self::$classMap[$className]))
<span class="ln">391</span>             include(self::$classMap[$className]);
<span class="ln">392</span>         else
<span class="ln">393</span>         {
<span class="ln">394</span>             if(strpos($className,&#039;\\&#039;)===false)
<span class="error"><span class="ln error-ln">395</span>                 include($className.&#039;.php&#039;);
</span><span class="ln">396</span>             else  // class name with namespace in PHP 5.3
<span class="ln">397</span>             {
<span class="ln">398</span>                 $namespace=str_replace(&#039;\\&#039;,&#039;.&#039;,ltrim($className,&#039;\\&#039;));
<span class="ln">399</span>                 if(($path=self::getPathOfAlias($namespace))!==false)
<span class="ln">400</span>                     include($path.&#039;.php&#039;);
<span class="ln">401</span>                 else
<span class="ln">402</span>                     return false;
<span class="ln">403</span>             }
<span class="ln">404</span>             return class_exists($className,false) || interface_exists($className,false);
<span class="ln">405</span>         }
<span class="ln">406</span>         return true;
<span class="ln">407</span>     }
</pre></div>    </div>

    <div class="traces">
        <h2>Stack Trace</h2>
</pre>

Any ideas as how do I get Yii shell running with yiimongodbsuite?

Thanks for this awesome job!!

**Comment by canni** [comment]
Hey,

there is no `Mongo` class in YMDS, all classes are prefixed with `EMongo`.

I suspect that You have different configuration for php and php-cli (command line interface)

Please ensure that mongo php extension in properly loaded in CLI (You can test it by invoking phpinfo() from CLI and see is there a mongo config section)

Ie. standard php installation in debian have 2 config files one for php module and one for the CLI interface

**Comment by lpanebr** [comment]
I installed mongo via ubuntu's apt-get..  Will check it and get back. Everything else works though..

**Comment by lpanebr** [comment]
hmm..  yep. Mongo does not appear on the CLI phpinfo(). Will find out how to install it. Thanks!

**Comment by lpanebr** [comment]
GREAT! All I needed to do was add the line:
`extension=mongo.so`
on the file:
`/etc/php5/cli/php.ini`

Thanks for this great work and for your help!!
