### ISSUE TITLE
weird error with Undefined Index...

### ISSUE THREAD

**Issue by lpanebr** [canni/YiiMongoDbSuite#29]
Hello again. Perhaps you can shred some light with this. I have two desktop computers where I code. The only diference is one is 64bit ubuntu and the other 32bit ubuntu both 10.04.

On the 32bit I get the following when I access admin views for exemple: http://cmsa/index.php?r=news/admin

```
<h1>PHP Error</h1> 

<p class="message"> 
    Undefined index: News   </p> 

<div class="source"> 
    <p class="file">/home/lpanebr/mysites/cmsa/protected/extensions/YiiMongoDbSuite/EMongoDocument.php(331)</p> 
    <div class="code"><pre><span class="ln">319</span>      * Get value of use cursor flag
```

<span class="ln">320</span>      *
<span class="ln">321</span>      \* It will return the nearest not null value in order:
<span class="ln">322</span>      \* - Object level
<span class="ln">323</span>      \* - Model level
<span class="ln">324</span>      \* - Glopal level (always set)
<span class="ln">325</span>      \* @return boolean
<span class="ln">326</span>      _/
<span class="ln">327</span>     public function getUseCursor()
<span class="ln">328</span>     {
<span class="ln">329</span>         if($this-&gt;useCursor !== null)
<span class="ln">330</span>             return $this-&gt;useCursor; // We have flag set, return it
<span class="error"><span class="ln error-ln">331</span>         if(self::$_models[get_class($this)]-&gt;useCursor !== null)
</span><span class="ln">332</span>             return self::$_models[get_class($this)]-&gt;useCursor; // Model have flag set, return it
<span class="ln">333</span>         return $this-&gt;getMongoDBComponent()-&gt;useCursor;
<span class="ln">334</span>     }
<span class="ln">335</span> 
<span class="ln">336</span>     /_*
<span class="ln">337</span>      \* Set object level value of use cursor flag
<span class="ln">338</span>      \* @param boolean $useCursor true|false value for use cursor flag
<span class="ln">339</span>      */
<span class="ln">340</span>     public function setUseCursor($useCursor)
<span class="ln">341</span>     {
<span class="ln">342</span>         $this-&gt;useCursor = ($useCursor == true);
<span class="ln">343</span>     }
</pre></div>    </div>

**Comment by canni** [comment]
You have to upgrade to the latest version of YMDS, this bug was fixed in commit 
b36d2e2eb8f09e09a568e55522f902335e60bd40

**Comment by lpanebr** [comment]
THANKS AGAIN!!! :-)
