### ISSUE TITLE
Issue with wrong __isset magic on embedded documents

### ISSUE THREAD

**Issue by alexey-detr-aksilon** [canni/YiiMongoDbSuite#31]
There is a possible problem with _isset magic function. Problem appears if we don't access to embedded document via $this->embedDocName. Instead we try to check property by isset($model->embedDocName).
So I don't completely understand how I should use isset operator. Does embedded doc exists any time despite existence of corresponding field in DB?

**Comment by canni** [comment]
With regular EMongoDocument, embeded documents are lazy loaded, i dont know a good solution, on how isset func should work on embedded docs, for now :/

**Comment by alexey-detr-aksilon** [comment]
Thanks for your answer.

I've found another solution for my case, it's a usage of empty() function like this:

<pre><code>empty($model->embedDocName)</code></pre>

But in general it may not be a proper solution.
Maybe your embedded docs architecture should be reviewed.

Best regards,
Alexey
