### ISSUE TITLE
Make EMongo compatible with CHtml::listData()

### ISSUE THREAD

**Issue by thyseus** [canni/YiiMongoDbSuite#32]
Hey, first let me say thanks to the great work so far. It makes me switching over to mongodb really soon in my project. 

Now my concern:

lets assume i have a collection 'address' that stores my addresses and an embedded
document to a document from the collection 'country', where my countries are saved. Speaking in MySQL, this would be a 1:N relation.

Now, if i want the user to choose the country in the address _form.php, i want to present a DropDownList, like this

CHtml::activeDropDownList($addressModel, 'country', CHtml::listData(Country::model()->findAll(), '_id', 'country_title'));

This works well when i specify a own, customized primary Key for the country collection. However, if i leave it to the standard, i have ObjectId(...) objects. These can not be automatically resolved by the listData function.

There are two solutions for that: either write your own implementation of ListData, that autoMagically gets the correct id, or in my opinion better, give the ObjectId() a magic **toString** method, that converts to a string automatically so the CHtml::listData() provided by yii can work with it.

I hope my concern is clear. What do you think about this ?

thyseus@gmail.com

**Comment by canni** [comment]
I'm currently killed with work :/ and YMDS is my hobby project only :/ when I'll find some free time I'll look through Yours ideas.

cheers

**Comment by thyseus** [comment]
no problem -> i will push some code that fixes it, so you have nothing to do :)

i plan on doing a lot with yii & mongo in the next months, so i can keep care a little bit of the project. oh yes and i am killed with work, too ;)

**Comment by canni** [comment]
I cannot add __toString method to ObjectId class, because this class is defined in Mongo PHP driver itself, to do this I'll have to cover ObjectId class with some new one, and thats leads to inconsistence with default driver behavior
