### ISSUE TITLE
gii-mongoCRUD generator not working with embedded documents

### ISSUE THREAD

**Issue by rajeshtomjoe** [canni/YiiMongoDbSuite#33]
i have been trying to generate code for model class user with embedded document useraddress(example provided by you),mongoCRUD generator works for non embedded document.
when i try to generate code for embedded document i get the following error 
array_keys() expects parameter 1 to be array, null given

on line EMongoEmbeddedDocument.php(267)
if($this->hasEmbeddedDocuments())
            {
                $names = array_merge($names, array_keys(self::$_embeddedConfig[get_class($this)]));
            }
could you please help me out with this

**Comment by canni** [comment]
Hey, this is not a bug, just not documented behavior, CRUD generator is not smart enough to generate CRUD (especially forms) for embedded documents, You have to comment out embedded config for time of generation process, and afterwards write forms for embedded documents by hand.

**Comment by rajeshtomjoe** [comment]
thanks
