### ISSUE TITLE
embedded documents loads only safe attributes

### ISSUE THREAD

**Issue by mrbig** [canni/YiiMongoDbSuite#5]
Attributes not marked safe in embedded document are not loaded by the find() methods.

This is caused by the default setAttribute method of CModel, that does not pass on the safeOnly parameter. To correct this I've overridden the setAttribute method in EMongoEmbeddedDocument.

Please check the commit at:
https://github.com/mrbig/YiiMongoDbSuite/commit/0578e5da71f804f8d7ea5a0d2e6ed86c040dc543

**Comment by canni** [comment]
Thx, for pointing that out, but i think fix should be applied to embeddedDocsInit method, i'll investigate this issue :)

**Comment by mrbig** [comment]
I'm open to discussion on the topic, my patch is just a proposal.

Of course embeddedDocsInit could be rewritten too, but if you see the other side of this: setAttributes($params, false) should work on the embedded document attributes also. Yii doesn't handle this case, since there the attributes can't be objects, so it's a don't care for them.

**Comment by mrbig** [comment]
sorry I've accidentally closed this issue, and can't find a way to reopen it. But it's still unsolved.

**Comment by canni** [comment]
OK, i've applied little modified version of Yours patch, i forgot that initEmbededDocs method is just for object creation, not more :)

**Comment by mrbig** [comment]
Thanks, I like your changes, it uses more of the parent implementation.
