### ISSUE TITLE
GeoSpatial Support

### ISSUE THREAD

**Issue by timatron** [canni/YiiMongoDbSuite#50]
Hi Guys,

I'm trying to see if I can use some of the geospatial features of mongodb through this suite. I've everything installed and working, just trying to do some of the less used mongodb calls like 

db.places.find( { loc : { $near : [50,50] , $maxDistance : 5 } } ).limit(20)

Where 50,50 would be a longitude and latitude. Got any ideas how I could port this into your yii suite?

Thanks!
-tim

http://www.mongodb.org/display/DOCS/Geospatial+Indexing

**Comment by timatron** [comment]
nm, just added a near opperator, easy peasy

danke

**Comment by inteist** [comment]
Can you please share this code as this is useful to others as well I am sure.

Thanks.

**Comment by timatron** [comment]
Here ya go! EASY PEASY! :)

```
    $criteria = new EMongoCriteria;
    $criteria->limit(1);
    $criteria->addCond('coordinates', 'near', array((float)$longitude,(float)$latitude));
    $cities = Cities::model()->find($criteria);
```
