### ISSUE TITLE
Call to a member function getConditions() on a non-object

### ISSUE THREAD

**Issue by josemartinez** [canni/YiiMongoDbSuite#9]
I'm wondering if its a bug or not, because you dont find without criteria but...

On EMongoDocument.php file line 670 you have

"public function find($criteria=null)"

then you do: 

"$criteria->getConditions()"

if criteria is null you get an error. Maybe check if its null before getConditions?

**Comment by canni** [comment]
I cannot reproduce this error :/ it works for me

$criteria variable in that line, should be populated with EMongoCriteria object by a applyScopes() method, witch is called with reference to parameter (Original Yii AR class doest the same trick, with applyScopes method)

**Comment by josemartinez** [comment]
Happy new year U2!
yes, you are right! I explain you a little what i did. 

I changed on my web application from MySQL to full MongoDb. So i have lines as: 

UsersDb::model()->find('LOWER(userLogin)=mylogin'); 

Obviously thats wrong because this request in MongoDb is not correct, but even if its not correct, with this request i do applyScopes with a string as $criteria (thats why $criteria->getConditions() crashes), and i thought you should catch this case.... but i'm wrong because we will not check in this function each type or developement errors..... if we send something different than an array or EMongoCriteria to applyScopes function, is a developper issue, not a conception issue (he should read the doc)

I hope i'm clear!

**Comment by canni** [comment]
OK, now I see, I've added a consistence check to applyScopes() method, in commit b38fd1959f4cce8853f4 It will be helpful in case of porting apps to the MongoDB.
